name: CI para App Python

on:
  push:
    branches: [ "main" ]

jobs:
  call-build-template:
    uses: LuanCristopher/github-ci-templates/.github/workflows/build-and-push-template.yml@main
    with:
      language: 'python'
      image-name: 'python-app'
      repo-path: '.'
      tag: ${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT_GIT_GITOPS: ${{ secrets.PAT_GIT_GITOPS }}